apiVersion: orchestrator.aiops.ibm.com/v1alpha1
kind: Installation
metadata:
  name: <NAME>
  namespace: <NAMESPACE>
spec:
  imagePullSecret: ibm-entitlement-key
  license:
    accept: true
  pakModules:
    - enabled: true
      name: aiManager
      config:
        - name: aimanager-operator
          spec:
            aimanager:
              aimanagerValues:
                flink:
                  ha:
                    enabled: false
                    storageClassName: <STORAGE_CLASS>
                postgres:
                  keeper:
                    resources:
                      limits:
                        cpu: 500m
                        memory: 512Mi
                      requests:
                        cpu: 100m
                        memory: 256Mi
                  livenessProbe:
                    failureThreshold: 5
                    initialDelaySeconds: 300
                    periodSeconds: 15
                    successThreshold: 1
                    timeoutSeconds: 15
                  persistence:
                    enabled: true
                    size: 20Gi
                    storageClass: <STORAGE_CLASS>
                  readinessProbe:
                    failureThreshold: 5
                    initialDelaySeconds: 300
                    periodSeconds: 15
                    successThreshold: 1
                    timeoutSeconds: 15
                  sentinel:
                    resources:
                      limits:
                        cpu: 500m
                        memory: 512Mi
                      requests:
                        cpu: 100m
                        memory: 256Mi
                  serviceAccount:
                    name: aimanager-operator
    - enabled: true
      name: aiopsFoundation
    - enabled: true
      name: applicationManager
      config:
        - name: noi-operator
          spec:
            noi:
              helmValuesASM:
                global.enableAllRoutes: true
              persistence:
                storageClassDB2: <STORAGE_CLASS>
  size: <ENV_SIZE>
  storageClass: '<STORAGE_CLASS>'
  storageClassLargeBlock: '<STORAGE_CLASS_LB>'
