kind: Deployment
apiVersion: apps/v1
metadata:
  name: iaf-core-operator-controller-manager
  namespace: openshift-operators
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: iaf-core-operator
      app.kubernetes.io/instance: iaf-core-operator
      app.kubernetes.io/managed-by: olm
      app.kubernetes.io/name: iaf-core-operator
      control-plane: controller-manager
      name: iaf-core-operator
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: iaf-core-operator
        app.kubernetes.io/instance: iaf-core-operator
        app.kubernetes.io/managed-by: olm
        app.kubernetes.io/name: iaf-core-operator
        control-plane: controller-manager
        name: iaf-core-operator
      annotations:
        olm.skipRange: '>=1.0.2 <1.1.0'
        operators.operatorframework.io/builder: operator-sdk-v1.2.0
        operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
        certified: 'false'
        olm.targetNamespaces: ''
        operatorframework.io/properties: >-
          {"properties":[{"type":"olm.gvk","value":{"group":"core.automation.ibm.com","kind":"AutomationUIConfig","version":"v1beta1"}},{"type":"olm.gvk","value":{"group":"core.automation.ibm.com","kind":"Cartridge","version":"v1beta1"}},{"type":"olm.package","value":{"packageName":"ibm-automation-core","version":"1.1.0"}}]}
        support: IBM
        alm-examples: |-
          [
            {
              "apiVersion": "core.automation.ibm.com/v1beta1",
              "kind": "AutomationUIConfig",
              "metadata": {
                "name": "automationuiconfig-sample"
              },
              "spec": {
                "description": "Sample Automationuiconfig CR",
                "license": {
                  "accept": false
                },
                "storage": {
                  "class": "\u003cYour_managed-nfs-storage\u003e"
                },
                "tls": {},
                "version": "v1.0"
              }
            },
            {
              "apiVersion": "core.automation.ibm.com/v1beta1",
              "kind": "Cartridge",
              "metadata": {
                "name": "cartridge-sample"
              },
              "spec": {
                "description": "Sample cartridge CR",
                "license": {
                  "accept": false
                },
                "version": "v1.0"
              }
            }
          ]
        capabilities: Seamless Upgrades
        olm.operatorNamespace: openshift-operators
        containerImage: >-
          icr.io/cpopen/iaf-core-operator@sha256:73f4a2940eb875b387ee0be936501a748163e2713c1c4b114c2517b26fe3767c
        createdAt: '2021-06-08T08:15:37'
        olmcahash: bc3004a41398a8018f6cc94115858642f6da4792ebfe645aa0e4d0518c6cd0d0
        categories: Automation
        description: Installs and manages IBM Common Services and UI
        olm.operatorGroup: global-operators
    spec:
      restartPolicy: Always
      serviceAccountName: iaf-core-operator-serviceaccount
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
      containers:
        - resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 150m
              memory: 200Mi
          readinessProbe:
            httpGet:
              path: /readyz
              port: 5555
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: manager
          command:
            - /manager
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5555
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.annotations[''olm.targetNamespaces'']'
            - name: HEALTH_IMAGES
              value: >
                1.1.0=cp.icr.io/cp/iaf-health-service@sha256:4f0229ea94f3b2420731a11e506b93063afba5e09029c202876533188db263dd
            - name: ZEN_JOB_IMAGES
              value: >
                1.1.0=cp.icr.io/cp/iaf-ui-customization@sha256:a642521e5325d364ff50b852c7255efbc371545195d65ea23637bcd2b45b2bb2
            - name: OPERATOR_CONDITION_NAME
              value: ibm-automation-core.v1.1.0
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - name: webhook-server
              containerPort: 9443
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: webhook-cert
              mountPath: /tmp/k8s-webhook-server/serving-certs
            - name: apiservice-cert
              mountPath: /apiserver.local.config/certificates
          terminationMessagePolicy: File
          image: >-
            icr.io/cpopen/iaf-core-operator@sha256:73f4a2940eb875b387ee0be936501a748163e2713c1c4b114c2517b26fe3767c
          args:
            - '--enable-leader-election'
      serviceAccount: iaf-core-operator-serviceaccount
      volumes:
        - name: cert
          secret:
            secretName: iaf-core-operator-controller-manager-service-cert
            defaultMode: 420
        - name: apiservice-cert
          secret:
            secretName: iaf-core-operator-controller-manager-service-cert
            items:
              - key: tls.crt
                path: apiserver.crt
              - key: tls.key
                path: apiserver.key
            defaultMode: 420
        - name: webhook-cert
          secret:
            secretName: iaf-core-operator-controller-manager-service-cert
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
            defaultMode: 420
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 600
